### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rizkytegar** [gemarkode/learn-react-js#2]
Hello, silahkan tulis bug apapun di sini

**Comment by rizkytegar** [comment]
![Screenshot from 2021-03-11 09-44-42](https://user-images.githubusercontent.com/55475891/110727944-bde69f80-824e-11eb-8593-a0af713d88d2.png)

JIka Gagal Compile, pastikan node module sudah di install.

ketikan :

`npm install`

maka node module akan terinstall.

**Comment by septiyp** [comment]
bug fixed and build new version
